### ISSUE TITLE
ERROR: No matching distribution found for pywin32==306

### ISSUE THREAD

**Issue by jhuvehicle** [StavC/Here-Comes-the-AI-Worm#1]
Hello,

I am having an issue when installing the requirements.txt file in the git repo:

ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)

ERROR: No matching distribution found for pywin32==306

I am assuming this can only be run on a windows machine?

(I have read your paper : “Here Comes The AI Worm: Unleashing Zero-click

Worms that Target GenAI-Powered Applications”

but I may need to read it again)

**Comment by StavC** [comment]
Hey, please try installing the package separately without the version.
pip install pywin32

The RAG-based worm ran on WINDOWS with these dependencies.

As for flow-steering, it was run on Linux virtual machines. I'll need to update a requirement file for them.

**Comment by jhuvehicle** [comment]
Collecting pywinpty==2.0.12 (from -r requirements.txt (line 115))
  Downloading pywinpty-2.0.12.tar.gz (27 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jhuvehicle** [comment]
![Worm_AI](https://github.com/StavC/ComPromptMized/assets/112336923/b42027ac-27cc-4866-bb87-b1714a3f7fea)

**Comment by jhuvehicle** [comment]
The Google Colab instance is using a linux operating system, I ended up removing the pywin32 from the requirements txt file but I obtained an error with pywinpty

**Comment by jhuvehicle** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 0.24.0 requires pandas<2.1.4,>=1.5.0, but you have pandas 2.2.1 which is incompatible.
gcsfs 2023.6.0 requires fsspec==2023.6.0, but you have fsspec 2024.2.0 which is incompatible.
google-colab 1.0.0 requires google-auth==2.27.0, but you have google-auth 2.28.1 which is incompatible.
google-colab 1.0.0 requires ipykernel==5.5.6, but you have ipykernel 6.29.2 which is incompatible.
google-colab 1.0.0 requires ipython==7.34.0, but you have ipython 8.18.1 which is incompatible.
google-colab 1.0.0 requires notebook==6.5.5, but you have notebook 7.1.0 which is incompatible.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.2.1 which is incompatible.
google-colab 1.0.0 requires tornado==6.3.3, but you have tornado 6.4 which is incompatible.
imageio 2.31.6 requires pillow<10.1.0,>=8.3.2, but you have pillow 10.2.0 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.1.1 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.25.3 which is incompatible.
Successfully installed Pygments-2.17.2 QtPy-2.4.1 SQLAlchemy-2.0.27 anyio-4.3.0 arrow-1.3.0 asttokens-2.4.1 async-lru-2.0.4 cachetools-5.3.2 colorama-0.4.6 comm-0.2.1 dataclasses-json-0.6.4 debugpy-1.8.1 decorator-5.1.1 distro-1.9.0 executing-2.0.1 faiss-cpu-1.7.4 fqdn-1.5.1 fsspec-2024.2.0 google-api-core-2.17.1 google-auth-2.28.1 googleapis-common-protos-1.62.0 grpcio-1.62.0 grpcio-status-1.62.0 h11-0.14.0 httpcore-1.0.4 httpx-0.27.0 importlib-metadata-7.0.1 ipykernel-6.29.2 ipython-8.18.1 ipywidgets-8.1.2 isoduration-20.11.0 jedi-0.19.1 json5-0.9.17 jsonpatch-1.33 jsonpointer-2.4 jsonschema-4.21.1 jupyter-1.0.0 jupyter-console-6.6.3 jupyter-events-0.9.0 jupyter-lsp-2.2.2 jupyter_client-8.6.0 jupyter_core-5.7.1 jupyter_server-2.12.5 jupyter_server_terminals-0.5.2 jupyterlab-4.1.2 jupyterlab_server-2.25.3 langchain-0.1.9 langchain-community-0.0.24 langchain-core-0.1.26 langchain-google-genai-0.0.9 langsmith-0.1.8 marshmallow-3.20.2 mistune-3.0.2 mypy-extensions-1.0.0 nbclient-0.9.0 nbconvert-7.16.1 nbformat-5.9.2 notebook-7.1.0 numpy-1.26.4 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.4.99 nvidia-nvtx-cu12-12.1.105 openai-1.12.0 orjson-3.9.15 overrides-7.7.0 packaging-23.2 pandas-2.2.1 pillow-10.2.0 protobuf-4.25.3 psutil-5.9.8 pure-eval-0.2.2 pydantic-2.6.2 python-json-logger-2.0.7 pytz-2024.1 pyzmq-25.1.2 qtconsole-5.5.1 rfc3339-validator-0.1.4 rfc3986-validator-0.1.1 sniffio-1.3.0 stack-data-0.6.3 terminado-0.18.0 tiktoken-0.6.0 tornado-6.4 traitlets-5.14.1 transformers-4.38.1 types-python-dateutil-2.8.19.20240106 typing-inspect-0.9.0 typing_extensions-4.9.0 tzdata-2024.1 uri-template-1.3.0 urllib3-2.2.1 widgetsnbextension-4.0.10 zipp-3.17.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by jhuvehicle** [comment]
I ended up removing the following from the requirements.txt file: pywinpty. If you think I can run the Flow Steering portion of this paper please let me know .

v/r

-Tulio

**Comment by jhuvehicle** [comment]
I was able to fix this, I am closing this issue.
