### ISSUE TITLE
Download LLaVa weights

### ISSUE THREAD

**Issue by jhuvehicle** [StavC/Here-Comes-the-AI-Worm#2]
You write in your REPO:

_You can download the model checkpoints from the [LLaVA repository](https://github.com/haotian-liu/LLaVA) and save them to the "models" folder. Save the weights in the "ComPromptMized/FlowSteering/llava/llava_weights" directory. In our experiments, we utilize the LLaVA-7B weights._

Which weights and checkpoints would you recommend?(To get your code running)

v/r

-Tulio

**Comment by StavC** [comment]
Hey Tulio, we used LLaVa-7B (https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#legacy-models-delta-weights). 
However, we assume that the same perturbation method will work on any other LLaVa model with minor adjustments.

**Comment by jhuvehicle** [comment]
thanks. closing this out.
