### ISSUE TITLE
Emails Data

### ISSUE THREAD

**Issue by jhuvehicle** [StavC/Here-Comes-the-AI-Worm#5]
If possible could you post a bigger dataset? I am able to run your code and I am currently using my own dataset for the RAG algorithm but I would like to see yours.

**Comment by StavC** [comment]
Hello,

Instead of utilizing a vast dataset sourced online, we simply collected emails by gathering them from our personal email accounts.

I'll work on anonymizing some of the emails and then publish them so you'll have some data to work with.
